pipeline {
    agent any
 tools {
        maven 'maven'
    }

    stages {
        stage('config-server') {
		dir('config-server') {
            steps {
                 sh 'mvn clean package -Dmaven.test.skip=true'

                }
            }
	}    
        }
		
    }
